/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CT75Ka26eWG
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function HomePage() {
  return (
    <div className="flex flex-col items-center w-full max-w-md p-4 mx-auto space-y-6 border rounded-lg">
      <h1 className="text-xl font-bold">Toban</h1>
      <div className="w-full p-4 space-y-6 border rounded-lg">
        <h2 className="text-lg font-semibold">Japan web3 Builders House</h2>
        <div className="flex items-center space-x-4">
          <div className="flex items-center justify-center w-16 h-16 bg-yellow-200 rounded-lg">
            <StarIcon className="w-8 h-8 text-blue-500" />
          </div>
          <div>
            <h3 className="text-md font-semibold">Cleaning</h3>
            <p className="text-sm text-gray-500">2024/8/11-2024/7/12</p>
            <p className="text-sm text-gray-500">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <div className="flex items-center justify-center w-16 h-16 bg-yellow-200 rounded-lg">
            <TriangleIcon className="w-8 h-8 text-blue-500" />
          </div>
          <div>
            <h3 className="text-md font-semibold">Committee</h3>
            <p className="text-sm text-gray-500">2024/5/11-2025/7/12</p>
            <p className="text-sm text-gray-500">
              Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            </p>
          </div>
        </div>
        <hr />
        <h2 className="text-lg font-semibold">Project Info</h2>
        <div className="flex items-center space-x-2">
          <UserIcon className="w-6 h-6 text-blue-500" />
          <p className="text-sm">15 members</p>
          <GitlabIcon className="w-6 h-6 text-blue-500" />
          <p className="text-sm">2 Surfer</p>
        </div>
        <div className="flex items-center space-x-4">
          <div className="flex flex-col items-center">
            <div className="flex items-center justify-center w-12 h-12 bg-yellow-200 rounded-lg">
              <StarIcon className="w-6 h-6 text-blue-500" />
            </div>
            <p className="text-sm">Cleaning</p>
          </div>
          <div className="flex flex-col items-center">
            <div className="flex items-center justify-center w-12 h-12 bg-yellow-200 rounded-lg">
              <TriangleIcon className="w-6 h-6 text-blue-500" />
            </div>
            <p className="text-sm">Committee</p>
          </div>
          <div className="flex flex-col items-center">
            <div className="flex items-center justify-center w-12 h-12 bg-yellow-200 rounded-lg">
              <SquareIcon className="w-6 h-6 text-blue-500" />
            </div>
            <p className="text-sm">Overlaps</p>
          </div>
          <div className="flex flex-col items-center">
            <div className="flex items-center justify-center w-12 h-12 bg-yellow-200 rounded-lg">
              <CircleIcon className="w-6 h-6 text-blue-500" />
            </div>
            <p className="text-sm">Fund</p>
          </div>
        </div>
        <Button variant="outline" className="w-12 h-12">
          <PlusIcon className="w-6 h-6 text-blue-500" />
        </Button>
      </div>
    </div>
  )
}

function CircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
    </svg>
  )
}


function GitlabIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  )
}


function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SquareIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}


function StarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function TriangleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M13.73 4a2 2 0 0 0-3.46 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
